### ISSUE TITLE
インフラ構成図作成

### ISSUE THREAD

**Issue by suzuki84g** [IkaProduction/RefreshList_dev#6]
Cacooを使用
EC2+RDB、非冗長、テスト環境を含む、DNSは一旦非考慮する旨を記載要

**Comment by suzuki84g** [comment]
![AWS](https://user-images.githubusercontent.com/38928546/68638156-fe8fb500-0543-11ea-8bea-3b70330ef89b.png)
一旦こんな感じで。IPとかは開発作りながら振ります。
冗長化は本番作り時にまた考えます。

**Comment by suzuki84g** [comment]
@otera05 レビューお願いします

**Comment by otera05** [comment]
構成としてはいいと思います！
懸念点は、RDSは個人で使うには料金が高いため、RDSの代わりにEC2インスタンスにMySQLをインストールしてDBサーバとして使う、とかがいいかもしれませんね。

以下はもう少し厳密な構成図を書くためのアドバイスです。
- EC2 と EBS はほぼ確実にセットな項目なので EBS を明記する必要はない
- Route53 はグローバルサービスなので Availability Zone よりも外側に配置される
- VPC を作ってパブリックサブネット、プライベートサブネットに分けると Good
  - この場合、EC2 をパブリックサブネットに、RDS をプライベートサブネットに配置するとセキュリティ的に Good です

**Comment by otera05** [comment]
ちょっと不格好ですけど、こういう図が書けるようになるといいですね！
参考までに！

![Untitled (6)](https://user-images.githubusercontent.com/17538499/68642805-a3b18a00-0552-11ea-9062-bc67f6c36f95.png)

**Comment by suzuki84g** [comment]
Reviewありがとうございます。

> 懸念点は、RDSは個人で使うには料金が高いため、RDSの代わりにEC2インスタンスにMySQLをインストールしてDBサーバとして使う、とかがいいかもしれませんね。

インターネットによるとRDS専用に使ったほうが圧倒的に安い、みたいなのを見たんですが、個人利用レベルだとそんなことないんですかね、ここは知見を伺いたい。そんなに変わらないなら「RDS使った」をやりたい気がしなくもないです。

ROUTE53は雑コピペした弊害ですね…確かにパブリック部分だ…。
論理書いてるのか物理書いてるのか概念書いてるのかよくわからなくなったので、一旦IP周りは省いちゃったんですよね。概ね認識通りだったので、あとは実際に触りながら後追いドキュメント（吐きそうな単語だ）でやってみます。助かりました！

**Comment by otera05** [comment]
RDS も Aurora を使わなければそこまで高くなかった（とさっき気づいた）
まぁ予算が許すのであれば RDS 使うのは全然OKだと思います。

ざっくり見積もれるサイト共有しときますね。
https://aws.noplan.cc/
